version: "3.3"

networks:
  proxy:
    external: true

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`monitor.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    networks:
      - proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  webspa:
    image: ghcr.io/mdhthahmd/dotnet-hosting/aspnetcore-spa:0.0.2
    container_name: web-spa
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webspa.entrypoints=web"
      - "traefik.http.routers.webspa.rule=Host(`webspa.localhost`)"
      - "traefik.http.services.webspa.loadbalancer.server.port=80"
